Tickets/sitcom 1120 Simple Conversion of Jupyternotebook.
lsst-sitcom/sitcomtn-143 pull request #1
Opened 2024-10-25 17:42 UTC by ykangastro

I directly converted the Jupyter Notebook to the technote for this version as there would be a chance that we need this notebook very soon. 

https://sitcomtn-143.lsst.io/v/SITCOM-1120/index.html

Now I am thinking that I will use tags (what you showed me before) so

**v0.1   - simply converted one from the original notebook  (this version)**

For v.0.2 - apply TN-102 structure with a little more description. 
1) move some functions to the separated Python code (and call the functions)
2) add an abstract, some background, and more descriptions
3) add just a few more descriptions and apply some structure on tn-102

2024-11-19 21:08 UTC, PaulinaLSST commented
Hi Yijung ! Thanks for this conversion.

2024-11-19 21:19 UTC, PaulinaLSST requested changes
A simple conversion is fine. I would suggest removing Case 3 and Case 4 at the end of the page, as they are not necessary for the general purpose of this script.

2025-01-21 19:33 UTC, kakoon commented
I changed the TN to old style (not using the ipynb) and Dominique reviewed.

2025-01-21 19:34 UTC, kakoon commented
I have changed the assignee to myself, and reviewer to Dominique

2025-01-22 09:56 UTC, boutigny approved these changes
Discussed some details with HyeYun on Slack. Everything is fine now.

2025-01-22 14:20 UTC, PaulinaLSST commented
Approved

2025-01-22 14:23 UTC, PaulinaLSST commented
Closed pull request by mistake, reopened.

2025-01-22 14:24 UTC, PaulinaLSST approved these changes

2025-01-24 22:23 UTC, merged